name: amazon_cognito_upload_plus
description: The amazon_cognito_upload_plus package is a Dart library designed to simplify and streamline the process of uploading files to Amazon S3 Bucket.
version: 0.0.3

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  amazon_cognito_identity_dart_2: ^3.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
flutter:
